remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: ["DARIUS LIUTAS"]
description: ["I'm Darius Jonas Valevicius, a neuroscientist, musician, amateur game developer, and artist based in Montreal.", "Now I'm testing out multi-line descriptions.", "\nThis one started with a newline."]